In [9]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier, GradientBoostingClassifier,AdaBoostClassifier
from sklearn import datasets 

from sklearn.model_selection import train_test_split
from sklearn import metrics

from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import confusion_matrix,classification_report
import pandas as pd
import numpy as np
from sklearn.metrics.cluster import adjusted_rand_score

In [10]:
#Carga de los datos
iris = datasets.load_iris()
X = iris.data
y = iris.target

#dividir el conjunto de datos en 70% de entrenamiento y 30% de prueba 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

#score ayuda a comprobar si el modelo está sobreajustado
score=[]
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)
classifier.score(X_train, y_train),classifier.score(X_test, y_test)

(1.0, 0.9777777777777777)

**Bagging**

In [11]:
#La puntuacion 1.0 muestra que esta sobreajustado
#usando baggin : random forest para resolver el sobreajuste
rf = RandomForestClassifier(n_estimators=100)
bag_clf = BaggingClassifier(base_estimator=rf, n_estimators=100,
                            bootstrap=True, n_jobs=-1,
                            random_state=42)

bag_clf.fit(X_train, y_train)
bag_clf.score(X_train,y_train),bag_clf.score(X_test,y_test)

(0.9809523809523809, 0.9777777777777777)

In [12]:
#predecir especies
bag_clf_y_pred=bag_clf.predict(X_test)
print(classification_report(y_test,bag_clf_y_pred))
print('\n')
print(confusion_matrix(y_test,bag_clf_y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.94      1.00      0.97        17
           2       1.00      0.92      0.96        12

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.98        45
weighted avg       0.98      0.98      0.98        45



[[16  0  0]
 [ 0 17  0]
 [ 0  1 11]]


**Boosting**

In [13]:
gb = GradientBoostingClassifier(n_estimators=100).fit(X_train, y_train)
gb.fit(X_train, y_train)
gb.score (X_test,y_test),gb.score (X_train,y_train)

(0.9777777777777777, 1.0)

In [14]:
#Al estar sobreajustado se usa adaboost
ad = AdaBoostClassifier(n_estimators=100, learning_rate=0.03)

ad.fit(X_train, y_train)
ad.score(X_train, y_train), ad.score(X_test, y_test)

(0.9142857142857143, 0.9777777777777777)

In [15]:
#predecir especies
ad_y_pred=ad.predict(X_test)
print(classification_report(y_test,ad_y_pred))
print('\n')
print(confusion_matrix(y_test,ad_y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.94      1.00      0.97        17
           2       1.00      0.92      0.96        12

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.98        45
weighted avg       0.98      0.98      0.98        45



[[16  0  0]
 [ 0 17  0]
 [ 0  1 11]]
